import type { Flag, TraceStep, EntityLink } from "@/lib/types";

export const MOCK_FLAGS: Flag[] = [
  {
    id: "flag-1",
    candidate_id: "cand-1",
    entity_link_id: "el-1",
    trace_id: "trace-1",
    confidence_unregistered: 0.95,
    status: "open",
    evidence_pdf_url: null,
    screenshot_url: null,
    notes: null,
    created_at: "2026-05-14T10:00:00Z",
    updated_at: "2026-05-14T10:00:00Z",
    candidate_listings: {
      id: "cand-1",
      platform: "airbnb",
      external_id: "AB-001",
      title: "Luksuzni apartman — Veli Varoš, Split",
      host_name: "Marko",
      neighborhood: "Veli Varoš",
      city: "Split",
      approx_lat: 43.5083,
      approx_lon: 16.4378,
      url: "https://airbnb.com/rooms/001",
      price_per_night: 145,
      beds: 4,
      guests: 8,
      photos: null,
      scraped_at: "2026-05-14T08:00:00Z",
    },
    agent_traces: {
      id: "trace-1",
      candidate_id: "cand-1",
      agent_type: "investigation",
      model: "claude-haiku-4-5-20251001",
      step_count: 5,
      final_verdict: "flagged",
      final_confidence: 0.05,
      final_breakdown: { neighborhood: -0.35, host_name: -0.12, beds: -0.08, hep: -0.18, vodovod: -0.07 },
      evidence_chain: [
        { step_index: 0, fact: "Kvart Veli Varoš pretraživanje — 0 podudaranja za 'Marko' s 4 kreveta", tool_called: "search_htz_registry" },
        { step_index: 1, fact: "Geocodiranje potvrđuje lokaciju u stambenoj zoni bez registriranih turističkih objekata", tool_called: "geocode" },
        { step_index: 2, fact: "Normalizacija: 'Marko' → 'marko', Veli Varoš → 'veli-varos'. Pretraga ponovljena — i dalje 0 rezultata", tool_called: "normalize_croatian" },
        { step_index: 3, fact: "HEP: prosječna potrošnja 14.2 kWh/dan u zadnja 3 mjeseca — tipično za zauzet apartman, ne za prazni", tool_called: "check_hep_consumption" },
        { step_index: 4, fact: "Vodovod: 8.4 m³/mj — 3× više od prosjeka praznog stana u zoni", tool_called: "check_vodovod_consumption" },
      ],
      total_tokens: 4120,
      total_cost_usd: 0.0018,
      started_at: "2026-05-14T09:00:00Z",
      completed_at: "2026-05-14T09:00:45Z",
    },
  },
  {
    id: "flag-2",
    candidate_id: "cand-2",
    entity_link_id: "el-2",
    trace_id: "trace-2",
    confidence_unregistered: 0.91,
    status: "open",
    evidence_pdf_url: null,
    screenshot_url: null,
    notes: null,
    created_at: "2026-05-14T10:01:00Z",
    updated_at: "2026-05-14T10:01:00Z",
    candidate_listings: {
      id: "cand-2",
      platform: "airbnb",
      external_id: "AB-002",
      title: "Studio uz more — Bačvice",
      host_name: "Ana",
      neighborhood: "Bačvice",
      city: "Split",
      approx_lat: 43.5055,
      approx_lon: 16.4501,
      url: "https://airbnb.com/rooms/002",
      price_per_night: 98,
      beds: 2,
      guests: 4,
      photos: null,
      scraped_at: "2026-05-14T08:00:00Z",
    },
    agent_traces: {
      id: "trace-2",
      candidate_id: "cand-2",
      agent_type: "investigation",
      model: "claude-haiku-4-5-20251001",
      step_count: 4,
      final_verdict: "flagged",
      final_confidence: 0.09,
      final_breakdown: { neighborhood: -0.28, photo_phash: -0.15, hep: -0.20 },
      evidence_chain: [
        { step_index: 0, fact: "Pretraga registra u Bačvicama — nema 'Ana' s 2 kreveta", tool_called: "search_htz_registry" },
        { step_index: 1, fact: "pHash usporedba — nema fotografija u registru za ovaj kvart", tool_called: "phash_compare" },
        { step_index: 2, fact: "HEP: 11.5 kWh/dan — kontinuirana zauzetost zadnja 4 mjeseca, suprotno 'praznom stanu'", tool_called: "check_hep_consumption" },
      ],
      total_tokens: 3340,
      total_cost_usd: 0.0014,
      started_at: "2026-05-14T09:01:00Z",
      completed_at: "2026-05-14T09:01:38Z",
    },
  },
  {
    id: "flag-3",
    candidate_id: "cand-3",
    entity_link_id: "el-3",
    trace_id: "trace-3",
    confidence_unregistered: 0.87,
    status: "open",
    evidence_pdf_url: null,
    screenshot_url: null,
    notes: null,
    created_at: "2026-05-14T10:02:00Z",
    updated_at: "2026-05-14T10:02:00Z",
    candidate_listings: {
      id: "cand-3",
      platform: "booking",
      external_id: "BK-003",
      title: "Apartments Sunce d.o.o. — Spinut",
      host_name: "Apartments Sunce d.o.o.",
      neighborhood: "Spinut",
      city: "Split",
      approx_lat: 43.5130,
      approx_lon: 16.4420,
      url: "https://booking.com/hotel/003",
      price_per_night: 210,
      beds: 8,
      guests: 16,
      photos: null,
      scraped_at: "2026-05-14T08:00:00Z",
    },
    agent_traces: {
      id: "trace-3",
      candidate_id: "cand-3",
      agent_type: "investigation",
      model: "claude-haiku-4-5-20251001",
      step_count: 6,
      final_verdict: "flagged",
      final_confidence: 0.13,
      final_breakdown: { neighborhood: -0.20, host_name: -0.25, beds: -0.15 },
      evidence_chain: [
        { step_index: 0, fact: "Sudski registar: 'Apartments Sunce d.o.o.' nije registrirano kao turistički subjekt u Splitu", tool_called: "search_sudski_registar" },
        { step_index: 1, fact: "HTZ registar Spinut — 8 kreveta, nema podudaranja s nazivom 'Sunce'", tool_called: "search_htz_registry" },
        { step_index: 2, fact: "pHash Hammingova udaljenost ≥ 20 za sve candidate fotografije — nema vizualnog podudaranja", tool_called: "phash_compare" },
      ],
      total_tokens: 5890,
      total_cost_usd: 0.0024,
      started_at: "2026-05-14T09:02:00Z",
      completed_at: "2026-05-14T09:02:52Z",
    },
  },
  {
    id: "flag-4",
    candidate_id: "cand-4",
    entity_link_id: "el-4",
    trace_id: "trace-4",
    confidence_unregistered: 0.82,
    status: "reviewed",
    evidence_pdf_url: null,
    screenshot_url: null,
    notes: null,
    created_at: "2026-05-14T10:03:00Z",
    updated_at: "2026-05-14T10:03:00Z",
    candidate_listings: {
      id: "cand-4",
      platform: "airbnb",
      external_id: "AB-004",
      title: "Pogled na more — Meje",
      host_name: "Ivan",
      neighborhood: "Meje",
      city: "Split",
      approx_lat: 43.5078,
      approx_lon: 16.4290,
      url: "https://airbnb.com/rooms/004",
      price_per_night: 175,
      beds: 3,
      guests: 6,
      photos: null,
      scraped_at: "2026-05-14T08:00:00Z",
    },
    agent_traces: {
      id: "trace-4",
      candidate_id: "cand-4",
      agent_type: "investigation",
      model: "claude-haiku-4-5-20251001",
      step_count: 5,
      final_verdict: "flagged",
      final_confidence: 0.18,
      final_breakdown: { neighborhood: -0.18, host_name: -0.10, photo_phash: -0.12 },
      evidence_chain: [
        { step_index: 0, fact: "Meje pretraga — 1 'Ivan' pronađen u registru, ali registrirani objekt ima 6 kreveta, oglas navodi 3", tool_called: "search_htz_registry" },
        { step_index: 1, fact: "pHash Hammingova udaljenost = 14 između candidate i registriranog objekta (prag < 8 za podudaranje)", tool_called: "phash_compare" },
        { step_index: 2, fact: "Geocodiranje: oglas i registrirani objekt udaljeni 340m — previše za isti objekt", tool_called: "geocode" },
      ],
      total_tokens: 4560,
      total_cost_usd: 0.0019,
      started_at: "2026-05-14T09:03:00Z",
      completed_at: "2026-05-14T09:03:41Z",
    },
  },
  {
    id: "flag-5",
    candidate_id: "cand-5",
    entity_link_id: "el-5",
    trace_id: "trace-5",
    confidence_unregistered: 0.76,
    status: "open",
    evidence_pdf_url: null,
    screenshot_url: null,
    notes: null,
    created_at: "2026-05-14T10:04:00Z",
    updated_at: "2026-05-14T10:04:00Z",
    candidate_listings: {
      id: "cand-5",
      platform: "airbnb",
      external_id: "AB-005",
      title: "Žnjan raj — uz plažu",
      host_name: "Petra",
      neighborhood: "Žnjan",
      city: "Split",
      approx_lat: 43.4990,
      approx_lon: 16.4600,
      url: "https://airbnb.com/rooms/005",
      price_per_night: 122,
      beds: 2,
      guests: 4,
      photos: null,
      scraped_at: "2026-05-14T08:00:00Z",
    },
    agent_traces: {
      id: "trace-5",
      candidate_id: "cand-5",
      agent_type: "investigation",
      model: "claude-haiku-4-5-20251001",
      step_count: 3,
      final_verdict: "flagged",
      final_confidence: 0.24,
      final_breakdown: { neighborhood: -0.30, host_name: -0.08 },
      evidence_chain: [
        { step_index: 0, fact: "Žnjan pretraga — 0 registriranih objekata za ime 'Petra'", tool_called: "search_htz_registry" },
      ],
      total_tokens: 2810,
      total_cost_usd: 0.0012,
      started_at: "2026-05-14T09:04:00Z",
      completed_at: "2026-05-14T09:04:29Z",
    },
  },
  // --- auto-flagged ≥90% ---
  {
    id: "flag-6",
    candidate_id: "cand-6",
    entity_link_id: "el-6",
    trace_id: "trace-6",
    confidence_unregistered: 0.97,
    status: "open",
    evidence_pdf_url: null,
    screenshot_url: null,
    notes: null,
    created_at: "2026-05-14T10:05:00Z",
    updated_at: "2026-05-14T10:05:00Z",
    candidate_listings: {
      id: "cand-6",
      platform: "booking",
      external_id: "BK-006",
      title: "Heritage Stay d.o.o. — Stari grad",
      host_name: "Heritage Stay d.o.o.",
      neighborhood: "Grad",
      city: "Split",
      approx_lat: 43.5088,
      approx_lon: 16.4412,
      url: "https://booking.com/hotel/006",
      price_per_night: 245,
      beds: 2,
      guests: 4,
      photos: null,
      scraped_at: "2026-05-14T08:00:00Z",
    },
    agent_traces: {
      id: "trace-6",
      candidate_id: "cand-6",
      agent_type: "investigation",
      model: "claude-haiku-4-5-20251001",
      step_count: 4,
      final_verdict: "flagged",
      final_confidence: 0.03,
      final_breakdown: { neighborhood: -0.40, host_name: -0.30, beds: -0.10 },
      evidence_chain: [
        { step_index: 0, fact: "Sudski registar: 'Heritage Stay d.o.o.' nije registrirano kao turistički subjekt u Splitu", tool_called: "search_sudski_registar" },
        { step_index: 1, fact: "Stari grad pretraga — 0 podudaranja za ovu tvrtku ili sličan naziv", tool_called: "search_htz_registry" },
      ],
      total_tokens: 5120,
      total_cost_usd: 0.0021,
      started_at: "2026-05-14T09:05:00Z",
      completed_at: "2026-05-14T09:05:58Z",
    },
  },
  {
    id: "flag-7",
    candidate_id: "cand-7",
    entity_link_id: "el-7",
    trace_id: "trace-7",
    confidence_unregistered: 0.93,
    status: "open",
    evidence_pdf_url: null,
    screenshot_url: null,
    notes: null,
    created_at: "2026-05-14T10:06:00Z",
    updated_at: "2026-05-14T10:06:00Z",
    candidate_listings: {
      id: "cand-7",
      platform: "airbnb",
      external_id: "AB-007",
      title: "Firule Beach Studio",
      host_name: "Karlo",
      neighborhood: "Firule",
      city: "Split",
      approx_lat: 43.5035,
      approx_lon: 16.4560,
      url: "https://airbnb.com/rooms/007",
      price_per_night: 110,
      beds: 2,
      guests: 4,
      photos: null,
      scraped_at: "2026-05-14T08:00:00Z",
    },
    agent_traces: {
      id: "trace-7",
      candidate_id: "cand-7",
      agent_type: "investigation",
      model: "claude-haiku-4-5-20251001",
      step_count: 3,
      final_verdict: "flagged",
      final_confidence: 0.07,
      final_breakdown: { neighborhood: -0.35, host_name: -0.18 },
      evidence_chain: [
        { step_index: 0, fact: "Firule pretraga — 0 registriranih objekata za ime 'Karlo'", tool_called: "search_htz_registry" },
        { step_index: 1, fact: "pHash — nema registriranih fotografija za Firule kvart", tool_called: "phash_compare" },
      ],
      total_tokens: 3010,
      total_cost_usd: 0.0013,
      started_at: "2026-05-14T09:06:00Z",
      completed_at: "2026-05-14T09:06:33Z",
    },
  },
  // --- na provjeri <90% ---
  {
    id: "flag-8",
    candidate_id: "cand-8",
    entity_link_id: "el-8",
    trace_id: "trace-8",
    confidence_unregistered: 0.68,
    status: "open",
    evidence_pdf_url: null,
    screenshot_url: null,
    notes: null,
    created_at: "2026-05-14T10:07:00Z",
    updated_at: "2026-05-14T10:07:00Z",
    candidate_listings: {
      id: "cand-8",
      platform: "airbnb",
      external_id: "AB-008",
      title: "Spinut Family Apartment",
      host_name: "Obitelj Tomić",
      neighborhood: "Spinut",
      city: "Split",
      approx_lat: 43.5120,
      approx_lon: 16.4390,
      url: "https://airbnb.com/rooms/008",
      price_per_night: 155,
      beds: 5,
      guests: 10,
      photos: null,
      scraped_at: "2026-05-14T08:00:00Z",
    },
    agent_traces: {
      id: "trace-8",
      candidate_id: "cand-8",
      agent_type: "investigation",
      model: "claude-haiku-4-5-20251001",
      step_count: 4,
      final_verdict: "flagged",
      final_confidence: 0.32,
      final_breakdown: { neighborhood: -0.15, host_name: -0.20, beds: 0.05 },
      evidence_chain: [
        { step_index: 0, fact: "Spinut pretraga — pronađena 'Obitelj Tomić' s 4 kreveta (oglas navodi 5)", tool_called: "search_htz_registry" },
        { step_index: 1, fact: "pHash Hammingova udaljenost = 10 — graničan slučaj, nije jasno podudaranje", tool_called: "phash_compare" },
      ],
      total_tokens: 3800,
      total_cost_usd: 0.0016,
      started_at: "2026-05-14T09:07:00Z",
      completed_at: "2026-05-14T09:07:41Z",
    },
  },
  {
    id: "flag-9",
    candidate_id: "cand-9",
    entity_link_id: "el-9",
    trace_id: "trace-9",
    confidence_unregistered: 0.58,
    status: "open",
    evidence_pdf_url: null,
    screenshot_url: null,
    notes: null,
    created_at: "2026-05-14T10:08:00Z",
    updated_at: "2026-05-14T10:08:00Z",
    candidate_listings: {
      id: "cand-9",
      platform: "airbnb",
      external_id: "AB-009",
      title: "Lovret mirni apartman",
      host_name: "Dubravka",
      neighborhood: "Lovret",
      city: "Split",
      approx_lat: 43.5160,
      approx_lon: 16.4340,
      url: "https://airbnb.com/rooms/009",
      price_per_night: 78,
      beds: 2,
      guests: 4,
      photos: null,
      scraped_at: "2026-05-14T08:00:00Z",
    },
    agent_traces: {
      id: "trace-9",
      candidate_id: "cand-9",
      agent_type: "investigation",
      model: "claude-haiku-4-5-20251001",
      step_count: 5,
      final_verdict: "flagged",
      final_confidence: 0.42,
      final_breakdown: { neighborhood: -0.10, host_name: -0.18, photo_phash: 0.12 },
      evidence_chain: [
        { step_index: 0, fact: "Lovret pretraga — pronađena 'Đ. Kovačević' soba s 2 kreveta, ime ne odgovara", tool_called: "search_htz_registry" },
        { step_index: 1, fact: "pHash Hammingova udaljenost = 9 — gotovo na pragu, potrebna vizualna provjera", tool_called: "phash_compare" },
      ],
      total_tokens: 4200,
      total_cost_usd: 0.0017,
      started_at: "2026-05-14T09:08:00Z",
      completed_at: "2026-05-14T09:08:49Z",
    },
  },
];

export const MOCK_TRACE_STEPS: Record<string, TraceStep[]> = {
  "trace-1": [
    {
      id: "step-1-0",
      trace_id: "trace-1",
      step_index: 0,
      tool_called: "search_htz_registry",
      tool_input: { neighborhood: "Veli Varoš", host_first_name: "Marko", beds: 4 },
      tool_output: { candidates: [], count: 0, message: "No registered units found matching criteria" },
      why: "Provjeravam je li oglas registriran u HTZ registru za kvart Veli Varoš s parametrima domaćina i broja kreveta.",
      updated_hypothesis: "Nema registriranog podudaranja. Pouzdanost da je neregistriran: visoka.",
      confidence_delta: -0.35,
      duration_ms: 210,
    },
    {
      id: "step-1-1",
      trace_id: "trace-1",
      step_index: 1,
      tool_called: "geocode",
      tool_input: { address_fragment: "Veli Varoš, Split" },
      tool_output: { lat: 43.5085, lon: 16.4380, display_name: "Veli Varoš, Split, Splitsko-dalmatinska županija", confidence: 0.9 },
      why: "Geocodiram lokaciju kako bih potvrdio da se oglas zaista nalazi u Veli Varošu, a ne samo tako navodi.",
      updated_hypothesis: "Lokacija potvrđena u Veli Varošu. Registra nema. Indikacija je jaka.",
      confidence_delta: -0.08,
      duration_ms: 340,
    },
    {
      id: "step-1-2",
      trace_id: "trace-1",
      step_index: 2,
      tool_called: "normalize_croatian",
      tool_input: { text: "Marko, Veli Varoš" },
      tool_output: { normalized: "marko, veli-varos", diacritics_removed: true, aliases_resolved: ["Veli Varoš → veli-varos"] },
      why: "Normaliziram ime i kvart i ponavljam pretragu kako bih isključio pogreške u dijakritičkim znakovima.",
      updated_hypothesis: "Čak i s normalizacijom — 0 rezultata. Zaključak: neregistrirano.",
      confidence_delta: -0.12,
      duration_ms: 45,
    },
    {
      id: "step-1-3",
      trace_id: "trace-1",
      step_index: 3,
      tool_called: "check_hep_consumption",
      tool_input: { lat: 43.5083, lon: 16.4378, window_days: 90 },
      tool_output: { avg_kwh_per_day: 14.2, baseline_empty_apartment_kwh_per_day: 1.8, occupancy_ratio: 7.9, period: "2026-02-13 → 2026-05-14" },
      why: "Provjeravam potrošnju struje (HEP) za adresu — prazan stan troši ~1.8 kWh/dan, a apartman u najmu 8–18 kWh/dan.",
      updated_hypothesis: "14.2 kWh/dan = ~8× više od praznog stana. Netko zaista boravi tamo — vrlo jak signal najma.",
      confidence_delta: -0.18,
      duration_ms: 420,
    },
    {
      id: "step-1-4",
      trace_id: "trace-1",
      step_index: 4,
      tool_called: "check_vodovod_consumption",
      tool_input: { lat: 43.5083, lon: 16.4378, window_months: 3 },
      tool_output: { avg_m3_per_month: 8.4, baseline_empty_apartment_m3: 2.5, occupancy_ratio: 3.4, period: "Feb–Apr 2026" },
      why: "Provjeravam potrošnju vode (Vodovod Split) — prazan stan ~2.5 m³/mj, apartman u najmu 6–12 m³/mj.",
      updated_hypothesis: "8.4 m³/mj — definitivno netko boravi. Kombinirano s 0 podudaranja u registru: visoka pouzdanost neregistriranog najma.",
      confidence_delta: -0.07,
      duration_ms: 380,
    },
  ],
  "trace-2": [
    {
      id: "step-2-0",
      trace_id: "trace-2",
      step_index: 0,
      tool_called: "search_htz_registry",
      tool_input: { neighborhood: "Bačvice", host_first_name: "Ana", beds: 2 },
      tool_output: { candidates: [], count: 0, message: "No registered units found in Bačvice matching 'Ana' with 2 beds" },
      why: "Tražim 'Ana' u HTZ registru za Bačvice s 2 kreveta.",
      updated_hypothesis: "Nema podudaranja — potencijalno neregistrirano.",
      confidence_delta: -0.28,
      duration_ms: 190,
    },
    {
      id: "step-2-1",
      trace_id: "trace-2",
      step_index: 1,
      tool_called: "phash_compare",
      tool_input: { candidate_photo_phashes: ["a3f2b1c4d5e6f789", "1122334455667788"], registered_id: null },
      tool_output: { match: false, min_hamming_distance: null, message: "No registered units in neighborhood to compare against" },
      why: "Pokušavam vizualno podudaranje fotografija, ali u registru nema objekata u Bačvicama.",
      updated_hypothesis: "Vizualna provjera nemoguća — nema referentnih fotografija. Ostaje oznaka neregistriranog.",
      confidence_delta: -0.15,
      duration_ms: 88,
    },
    {
      id: "step-2-2",
      trace_id: "trace-2",
      step_index: 2,
      tool_called: "check_hep_consumption",
      tool_input: { lat: 43.5055, lon: 16.4501, window_days: 120 },
      tool_output: { avg_kwh_per_day: 11.5, baseline_empty_apartment_kwh_per_day: 1.8, occupancy_ratio: 6.4, period: "2026-01-14 → 2026-05-14" },
      why: "Provjeravam HEP potrošnju struje — pokazatelj stvarne zauzetosti adrese.",
      updated_hypothesis: "Kontinuirana visoka potrošnja zadnja 4 mjeseca — netko boravi cijelo vrijeme. Vrlo jak signal aktivnog najma.",
      confidence_delta: -0.20,
      duration_ms: 395,
    },
  ],
  "trace-3": [
    {
      id: "step-3-0",
      trace_id: "trace-3",
      step_index: 0,
      tool_called: "search_sudski_registar",
      tool_input: { company_name: "Apartments Sunce d.o.o." },
      tool_output: { found: false, message: "No company 'Apartments Sunce d.o.o.' found in Sudski registar for Split" },
      why: "Oglas prikazuje naziv tvrtke — provjeravam je li registrirana kao turistički subjekt.",
      updated_hypothesis: "Tvrtka nije registrirana u sudskom registru. Jaki signal neregistriranog poslovanja.",
      confidence_delta: -0.25,
      duration_ms: 520,
    },
    {
      id: "step-3-1",
      trace_id: "trace-3",
      step_index: 1,
      tool_called: "search_htz_registry",
      tool_input: { neighborhood: "Spinut", beds: 8 },
      tool_output: { candidates: [{ id: "reg-999", name: "Apartmani Sunčani", owner: "Sunčić Josip", beds: 6 }], count: 1 },
      why: "Tražim u registru za Spinut s 8 kreveta kako bih pronašao moguće podudaranje.",
      updated_hypothesis: "Pronašao sličan naziv 'Apartmani Sunčani', ali 6 vs 8 kreveta i različito ime vlasnika.",
      confidence_delta: -0.20,
      duration_ms: 215,
    },
    {
      id: "step-3-2",
      trace_id: "trace-3",
      step_index: 2,
      tool_called: "phash_compare",
      tool_input: { candidate_photo_phashes: ["deadbeef12345678"], registered_id: "reg-999" },
      tool_output: { match: false, min_hamming_distance: 22, message: "Hamming distance 22 — no visual match (threshold: 8)" },
      why: "Vizualno uspoređujem fotografije sa sličnim registriranim objektom kako bih isključio podudaranje.",
      updated_hypothesis: "Hammingova udaljenost 22 — definitivno nisu isti objekt. Zaključak: neregistrirano.",
      confidence_delta: -0.15,
      duration_ms: 310,
    },
  ],
  "trace-4": [
    {
      id: "step-4-0",
      trace_id: "trace-4",
      step_index: 0,
      tool_called: "search_htz_registry",
      tool_input: { neighborhood: "Meje", host_first_name: "Ivan", beds: 3 },
      tool_output: { candidates: [{ id: "reg-101", name: "Apartman Ivan", owner: "Kovač Ivan", beds: 6, address: "Šetalište Ivana Meštrovića 22" }], count: 1 },
      why: "Tražim 'Ivan' u Mejama s 3 kreveta — postoji jedan kandidat, ali s 6 kreveta.",
      updated_hypothesis: "Pronašao 'Ivan Kovač' ali 6 kreveta vs 3 u oglasu. Možda je oglas podcijenio kapacitet — ili je to drugi objekt.",
      confidence_delta: -0.18,
      duration_ms: 230,
    },
    {
      id: "step-4-1",
      trace_id: "trace-4",
      step_index: 1,
      tool_called: "phash_compare",
      tool_input: { candidate_photo_phashes: ["f0f0f0aa55aa55aa"], registered_id: "reg-101" },
      tool_output: { match: false, min_hamming_distance: 14, message: "Hamming distance 14 — no match (threshold: 8)" },
      why: "Vizualno uspoređujem s registriranim objektom Ivana Kovača.",
      updated_hypothesis: "Hammingova udaljenost 14 — fotografije nisu iste. Vjerojatno su to dva različita objekta.",
      confidence_delta: -0.12,
      duration_ms: 290,
    },
    {
      id: "step-4-2",
      trace_id: "trace-4",
      step_index: 2,
      tool_called: "geocode",
      tool_input: { address_fragment: "Šetalište Ivana Meštrovića 22, Split" },
      tool_output: { lat: 43.5041, lon: 16.4188, display_name: "Šetalište Ivana Meštrovića 22, Meje, Split", confidence: 0.95 },
      why: "Geocodiram adresu registriranog objekta i uspoređujem s pin-om oglasa.",
      updated_hypothesis: "Registrirani objekt je 340m od pina oglasa — prevelika udaljenost. Potvrđujem da su to različiti objekti.",
      confidence_delta: -0.10,
      duration_ms: 380,
    },
  ],
  "trace-5": [
    {
      id: "step-5-0",
      trace_id: "trace-5",
      step_index: 0,
      tool_called: "search_htz_registry",
      tool_input: { neighborhood: "Žnjan", host_first_name: "Petra", beds: 2 },
      tool_output: { candidates: [], count: 0, message: "No registered units in Žnjan for host 'Petra'" },
      why: "Provjeravam registar za Žnjan — ovo je rubno područje grada s malo registriranih objekata.",
      updated_hypothesis: "Nema registriranih objekata za 'Petra' u Žnjanu. Zaključak: neregistrirano.",
      confidence_delta: -0.38,
      duration_ms: 175,
    },
  ],
};

export const MOCK_ENTITY_LINKS: Record<string, EntityLink> = {
  "flag-1": {
    id: "el-1",
    candidate_id: "cand-1",
    registered_id: null,
    verdict: "unmatched",
    confidence: 0.05,
    match_signals: {
      neighborhood: { fired: true, score: 0.0, evidence: "0 podudaranja u Veli Varošu za 'Marko' s 4 kreveta" },
      host_name: { fired: true, score: 0.0, evidence: "Ime 'Marko' nije pronađeno u HTZ registru za ovaj kvart" },
      beds: { fired: true, score: 0.0, evidence: "Nijedan registrirani objekt nema 4 kreveta u ovom kvartu" },
    },
    composite_key: { kvart: "veli-varos", beds: 4, host_first_name: "marko" },
    trace_id: "trace-1",
    matched_at: "2026-05-14T09:00:45Z",
  },
  "flag-2": {
    id: "el-2",
    candidate_id: "cand-2",
    registered_id: null,
    verdict: "unmatched",
    confidence: 0.09,
    match_signals: {
      neighborhood: { fired: true, score: 0.0, evidence: "0 podudaranja u Bačvicama" },
      photo_phash: { fired: true, score: 0.0, evidence: "Nema referentnih fotografija u registru" },
    },
    composite_key: { kvart: "bacvice", beds: 2, host_first_name: "ana" },
    trace_id: "trace-2",
    matched_at: "2026-05-14T09:01:38Z",
  },
  "flag-3": {
    id: "el-3",
    candidate_id: "cand-3",
    registered_id: null,
    verdict: "unmatched",
    confidence: 0.13,
    match_signals: {
      host_name: { fired: true, score: 0.0, evidence: "Tvrtka nije u sudskom registru" },
      neighborhood: { fired: true, score: 0.1, evidence: "Sličan naziv 'Apartmani Sunčani' — ali različit vlasnik i kapacitet" },
      beds: { fired: true, score: 0.1, evidence: "8 kreveta oglas vs 6 u registru — neslaganje" },
      photo_phash: { fired: true, score: 0.0, evidence: "Hammingova udaljenost 22 — nema vizualnog podudaranja" },
    },
    composite_key: { kvart: "spinut", beds: 8, host_first_name: null },
    trace_id: "trace-3",
    matched_at: "2026-05-14T09:02:52Z",
  },
  "flag-4": {
    id: "el-4",
    candidate_id: "cand-4",
    registered_id: "reg-101",
    verdict: "unmatched",
    confidence: 0.18,
    match_signals: {
      neighborhood: { fired: true, score: 0.5, evidence: "Pronađen Ivan Kovač u Mejama — ali kapacitet se ne podudara" },
      host_name: { fired: true, score: 0.6, evidence: "Ime 'Ivan' podudara se fuzzy — ali to može biti slučajnost" },
      beds: { fired: true, score: 0.0, evidence: "3 kreveta oglas vs 6 u registru — značajno neslaganje" },
      photo_phash: { fired: true, score: 0.1, evidence: "Hammingova udaljenost 14 — nije vizualno podudaranje" },
    },
    composite_key: { kvart: "meje", beds: 3, host_first_name: "ivan" },
    trace_id: "trace-4",
    matched_at: "2026-05-14T09:03:41Z",
  },
  "flag-5": {
    id: "el-5",
    candidate_id: "cand-5",
    registered_id: null,
    verdict: "unmatched",
    confidence: 0.24,
    match_signals: {
      neighborhood: { fired: true, score: 0.0, evidence: "0 registriranih objekata u Žnjanu za 'Petra'" },
      host_name: { fired: true, score: 0.0, evidence: "Ime 'Petra' nije u registru" },
    },
    composite_key: { kvart: "znjan", beds: 2, host_first_name: "petra" },
    trace_id: "trace-5",
    matched_at: "2026-05-14T09:04:29Z",
  },
};
